#include "UnrealTrace.h"

#include "Trace/BlockPool.cpp"
#include "Trace/Channel.cpp"
#include "Trace/Codec.cpp"
#include "Trace/Control.cpp"
#include "Trace/EventNode.cpp"
#include "Trace/Field.cpp"
#include "Trace/TlsBuffer.cpp"
#include "Trace/Trace.cpp"
#include "Trace/Writer.cpp"
#include "Trace/Detail/Windows/WindowsTrace.cpp"
